routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::group(['middleware' => ['auth', 'checkRole:admin,user']], function() {
    Route::get('/dashboard', 'DashboardController@index')->name('dashboard.index');
    Route::get('/kasmasuk/json', 'KasMasukController@dashboard')->name('kasmasuk.dashboard');
    Route::resource('kasmasuk', 'KasMasukController');
    Route::get('/exportpdf', 'KasMasukController@exportpdf')->name('kasmasuk.exportpdf');
    Route::get('/exportpdfperiode', 'KasMasukController@exportpdfperiode')->name('kasmasuk.exportpdfperiode');
    Route::get('/exportexcel', 'KasMasukController@exportExcel')->name('kasmasuk.exportexcel');
    Route::get('/exportexcelper', 'KasMasukController@exportexcelper')->name('kasmasuk.exportexcelper');

    Route::get('/kaskeluar/json', 'KasKeluarController@dashboard')->name('kaskeluar.dashboard');
    Route::resource('kaskeluar','KasKeluarController');
    Route::get('/exportpdfkel', 'KasKeluarController@exportpdfkel')->name('kaskeluar.exportpdfkel');
    Route::get('/exportpdfperiodekel', 'KasKeluarController@exportpdfperiodekel')->name('kaskeluar.exportpdfperiodekel');
    Route::get('/exportexcelkel', 'KasKeluarController@exportExcelkel')->name('kaskeluar.exportexcelkel');
    Route::get('/exportexcelperkel', 'KasKeluarController@exportexcelperkel')->name('kaskeluar.exportexcelperkel');

    Route::get('/rekapitulasi','RekapitulasiController@index')->name('rekapitulasi.index');
    Route::get('/exportpdfrekap', 'RekapitulasiController@exportpdfrekap')->name('rekapitulasi.exportpdfrekap');
    Route::get('/exportpdfperioderekap', 'RekapitulasiController@exportpdfperioderekap')->name('rekapitulasi.exportpdfperioderekap');

    Route::get('/dashboarduser', 'ManajemenUserController@dashboard')->name('user.dashboard');
    Route::resource('/user', 'ManajemenUserController');

});
Route::group(['middleware' => ['auth', 'checkRole:admin,user']], function() {
     Route::get('/dashboard', 'DashboardController@index')->name('dashboard.index');
     Route::get('/dashboard', 'DashboardController@index')->name('dashboard.index');
     Route::get('/kasmasuk/json', 'KasMasukController@dashboard')->name('kasmasuk.dashboard');
     Route::resource('kasmasuk', 'KasMasukController');
     Route::get('/exportpdf', 'KasMasukController@exportpdf')->name('kasmasuk.exportpdf');
     Route::get('/exportpdfperiode', 'KasMasukController@exportpdfperiode')->name('kasmasuk.exportpdfperiode');
     Route::get('/exportexcel', 'KasMasukController@exportExcel')->name('kasmasuk.exportexcel');
     Route::get('/exportexcelper', 'KasMasukController@exportexcelper')->name('kasmasuk.exportexcelper');

     Route::get('/kaskeluar/json', 'KasKeluarController@dashboard')->name('kaskeluar.dashboard');
     Route::resource('kaskeluar','KasKeluarController');
     Route::get('/exportpdfkel', 'KasKeluarController@exportpdfkel')->name('kaskeluar.exportpdfkel');
     Route::get('/exportpdfperiodekel', 'KasKeluarController@exportpdfperiodekel')->name('kaskeluar.exportpdfperiodekel');
     Route::get('/exportexcelkel', 'KasKeluarController@exportExcelkel')->name('kaskeluar.exportexcelkel');
     Route::get('/exportexcelperkel', 'KasKeluarController@exportexcelperkel')->name('kaskeluar.exportexcelperkel');

     Route::get('/rekapitulasi','RekapitulasiController@index')->name('rekapitulasi.index');
     Route::get('/exportpdfrekap', 'RekapitulasiController@exportpdfrekap')->name('rekapitulasi.exportpdfrekap');
     Route::get('/exportpdfperioderekap', 'RekapitulasiController@exportpdfperioderekap')->name('rekapitulasi.exportpdfperioderekap');
});

app/Kasmasuk.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Kasmasuk extends Model
{
   protected $fillable = [
   	'tgl_kas_masuk',
   	'nama',
   	'keterangan',
   	'jumlah',
   ];
}

app/Http/Controllers/KasMasukController.php
<?php

namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use Yajra\Datatables\Datatables;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;
use App\Kas;
use Carbon\Carbon;
use DB;
use Alert;
use PDF;
use Excel;
class KasMasukController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function dashboard(Request $request)
    {
      if ($request->ajax()) {
        // $from = $request->get('tgl');
        // $to = $request->get('created_at');

        $kasmasuk = Kas::all()->where('jenis','masuk');
                  // ->whereBetween('tgl', [$from, $to])
        
        // $kasmasuk = Kas::whereBetween('tgl', [$from, $to])->where('jenis','masuk')->get();

        // dd($kasmasuk);

        return Datatables::of($kasmasuk)
        ->addColumn('action', function($kasmasuk){
          $action = '<a href="'. route('kasmasuk.edit', base64_encode($kasmasuk->id)) .'" data-toggle="tooltip" data-placement="top" title="Ubah" class="btn btn-xs btn-primary btn-border btn-round"><i class="fa fa-edit" aria-hidden="true"></i></a>&nbsp;';
          $action .= '<div class="pull-right" style="margin-right: 20%">';
          $action .= \Form::open(['url'=> route('kasmasuk.destroy', $kasmasuk->id),'method'=>'delete', 'id' => 'form_id']);
          $action .= "<button type='submit'  class='btn btn-xs btn-round btn-danger'><i class='fas fa-trash-alt'></i></button>";
          $action .= \Form::close();
          $action .= '</div>';
          return $action;
        })
        ->editColumn('tgl', function($tgl){
          return date('d F Y', strtotime($tgl->tgl));
        })
        ->editColumn('jumlah', function($jumlah){
          return 'Rp.' . number_format($jumlah->jumlah);
        })
        ->make(true);
      }

      
    }
    public function index()
    {
       $kasmasuk = Kas::all()->where('jenis','masuk');
       return view('kasmasuk.index', compact('kasmasuk', 'totalmasuk'));


    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

      $this->validate($request, [
        'tgl' => 'required',
        'nama'=> 'required',
        'keterangan'=> 'required',
        'jumlah'=>'required'
      ]);

      $kasmasuk = new Kas;
      $kasmasuk->tgl = $request->tgl;
      $kasmasuk->nama = $request->nama;
      $kasmasuk->keterangan = $request->keterangan;
      $kasmasuk->jumlah = $request->jumlah;
      $kasmasuk->jenis  = 'masuk';
      $kasmasuk->masuk  = $request->jumlah;
      $kasmasuk->keluar  = '0';
      $kasmasuk->save();

      alert()->success('Menambahkan Kas Masuk','Berhasil')->persistent('Close');
      return redirect()->route('kasmasuk.index');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
      
      $kasmasuk = Kas::find(base64_decode($id));
      return view('kasmasuk.edit', compact('kasmasuk'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      $this->validate($request, [
        'tgl' => 'required',
        'nama'=> 'required',
        'keterangan'=> 'required',
        'jumlah'=>'required'
      ]);
      $kasmasuk = Kas::find($id);
      $kasmasuk->tgl = $request->tgl;
      $kasmasuk->nama = $request->nama;
      $kasmasuk->keterangan = $request->keterangan;
      $kasmasuk->jumlah = $request->jumlah;
      $kasmasuk->jenis  = 'masuk';
      $kasmasuk->masuk  = $request->jumlah;
      $kasmasuk->keluar  = '0';
      $kasmasuk->save();
      alert()->success('Mengupdate Kas masuk', 'Berhasil')->persistent('close');
      return redirect()->route('kasmasuk.index');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      $kasmasuk = Kas::find($id);
      $kasmasuk->delete();
      alert()->success('Menghapus Kas masuk', 'Berhasil')->persistent('close');
      return redirect()->route('kasmasuk.index');
    }
    public function exportpdf()
    {
      $kasmasuk = Kas::all()->where('jenis','masuk');
      $pdf = PDF::loadview('kasmasuk.exportpdf.jumlahpemasukan',['kasmasuk'=>$kasmasuk]);
      return $pdf->setPaper('a4')->download("jumlahpemasukan.pdf");
    }

    public function exportpdfperiode(Request $request)
    {   
      $from = $request->get('tgl');
      $to   = $request->get('created_at');
      $kasmasuk = Kas::whereBetween('tgl', [$from, $to])->where('jenis','masuk')->get();

      // dd($kasmasuk);                     
      $pdf = PDF::loadview('kasmasuk.exportpdf.jumlahpemasukanper',['kasmasuk'=>$kasmasuk, 'from' => $from, 'to' => $to]);
      return $pdf->setPaper('a4')->download("jumlahpemasukanper.pdf");            

    }

    public function exportExcel()
    {
      $kasmasuk = Kas::all()->where('jenis','masuk');
      \Excel::create('Laporan Kas Masuk', function($excel) use ($kasmasuk){
        $excel->setTitle('Laporan Kas Masuk');
        $excel->sheet('Data Pemasukan', function($sheet) use ($kasmasuk){
          $row = 1;
          $sheet->row($row, [
            'Tanggal',
            'Nama',
            'Keterangan',
            'Jumlah'
          ]);
          foreach ($kasmasuk as $item) {
            $sheet->row(++$row, [
             date('d F Y', strtotime($item->tgl)),
             $item->nama,
             $item->keterangan,
             'Rp.' . format_rupiah($item->jumlah)
           ]);
          }
        });
      })->export('xls');
    }

    public function exportexcelper(Request $request)
    {
      $from = $request->get('tgl');
      $to   = $request->get('created_at');
      $kasmasuk = Kas::whereBetween('tgl',[$from, $to])->where('jenis','masuk')->get();
      \Excel::create('Laporan Kas Masuk Per Periode', function($excel) use ($kasmasuk){
        $excel->setTitle('Laporan Kas Masuk Periode');
        $excel->sheet('Data Pemasukan Periode', function($sheet) use ($kasmasuk){
          $row = 1;
          $sheet->row($row, [
            'Tanggal',
            'Nama',
            'Keterangan',
            'Jumlah'
          ]);
          foreach ($kasmasuk as $item) {
            $sheet->row(++$row, [
             date('d F Y', strtotime($item->tgl)),
             $item->nama,
             $item->keterangan,
             'Rp.' . number_format($item->jumlah)
           ]);
          }
        });
      })->export('xls'); 
    }
    

  }

resources/views/kasmasuk/_form.blade.php
<form action="{{ route('kasmasuk.store') }}" method="post">
	{{ csrf_field() }}
	<div class="form-group">
		<label for="pillInput">Tanggal Kas Masuk</label>
		<input type="date" name="tgl" autocomplete="true" class="form-control input-pill"  id="pillInput" placeholder="" required>
	</div>

	<div class="form-group">
		<label for="pillInput">Nama</label>
		<input type="text" name="nama" class="form-control input-pill"  id="pillInput" placeholder="Nama" required>
	</div>

	<div class="form-group">
		<label for="pillInput">Keterangan</label>
		<input type="text" name="keterangan" class="form-control input-pill" id="pillInput" placeholder="Keterangan" required>
	</div>
	<div class="form-group">
		<label for="pillInput">Jumlah</label>
		<input type="number" name="jumlah" class="form-control input-pill" id="pillInput" placeholder="Jumlah" required>
	</div>
	<br>
	<div class="modal-footer">

		<button type="submit" class="btn btn-sm btn-primary "><i class="fas fa-save"></i> Simpan</button>
		<button type="button" class="btn btn-sm btn-primary btn-border" data-dismiss="modal">Batal</button>
	</div>
</form>

resources/views/kasmasuk/edit.blade.php
@extends('layouts.master')
@section('title','Edit Data Kas Masuk')
@section('content')
<div class="content">
	<div class="page-inner">
		<div class="page-header">
			<h4 class="page-title"><i class="far fa-file-alt"></i> Kas Masuk</h4>
			<ul class="breadcrumbs">
				<li class="nav-home">
					<a href="{{ route('dashboard.index') }}">
						<i class="flaticon-home"></i>
					</a>
				</li>
				<li class="separator">
					<i class="flaticon-right-arrow"></i>
				</li>
				<li class="nav-item">
					<a href="#"><i class="far fa-file-alt"></i> Kas Masuk</a>
				</li>
				<li class="separator">
					<i class="flaticon-right-arrow"></i>
				</li>
				<li class="nav-item">
					<a href="#"><i class="fas fa-info-circle"></i> List Kas Masuk</a>
				</li>
				<li class="separator">
					<i class="flaticon-right-arrow"></i>
				</li>
				<li class="nav-item">
					<a href="#"><i class="fas fa-edit"></i> Ubah Kas Masuk</a>
				</li>
			</ul>
		</div>
		<div class="row">
			<div class="col-md-12">
				<div class="card">
					<div class="card-header">
						<h4 class="card-title"><i class="fas fa-edit"></i> Ubah Kas Masuk</h4>
					</div>
					
					<div class="card-body">
						<form action="{{ route('kasmasuk.update', $kasmasuk->id) }}" method="post">
							{{ csrf_field() }}
							{{ method_field('put') }}
							<div class="form-group">
								<label for="">Tgl Kas Masuk</label>
								<input type="date" name="tgl" value="{{ $kasmasuk->tgl }}" class="form-control" id=""  placeholder="Tgl Kas Masuk">
							</div>
							<div class="form-group">
								<label for="">nama</label>
								<input type="text" name="nama" value="{{ $kasmasuk->nama }}" class="form-control"  placeholder="nama">
							</div>
							<div class="form-group">
								<label for="">Keterangan</label>
								<input type="text" name="keterangan" value="{{ $kasmasuk->keterangan }}" class="form-control"  placeholder="Keterangan">
							</div>
							<div class="form-group">
								<label for="">Jumlah</label>
								<input type="text" name="jumlah" value="{{ $kasmasuk->jumlah }}" class="form-control"  placeholder="Jumlah">
							</div>
							<br>
							<div class="box-header" style="margin-left: 14px;">
								<button type="submit" class="btn btn-sm btn-info"><i class="fas fa-save"></i> Simpan</button>
								<a href="{{ route('kasmasuk.index') }}" class="btn btn-sm btn-warning" title="">Kembali</a>
							</div>
							
						</form>
					</div>
				</div>
			</div>
			
		</div>
	</div>
</div>
@endsection

resources/views/kasmasuk/exportexcel.blade.php
 <div class="modal fade" id="exampleModalExcel" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="exampleModalLabel"><i class="fas fa-user-plus"></i>  Tambah Donatur</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				@include('kasmasuk.exportexcel._formexcel')
			</div>		  
		</div>
	</div>
</div>	

resources/views/kasmasuk/index.blade.php
@extends('layouts.master')
@section('title','Data Kas Masuk')
@section('content')
<div class="content">
	<div class="page-inner">
		<div class="page-header">
			<h4 class="page-title"><i class="far fa-file-alt"></i> Kas Masuk</h4>
			<ul class="breadcrumbs">
				<li class="nav-home">
					<a href="{{ route('dashboard.index') }}">
						<i class="flaticon-home"></i>
					</a>
				</li>
				<li class="separator">
					<i class="flaticon-right-arrow"></i>
				</li>
				<li class="nav-item">
					<a href="#"><i class="far fa-file-alt"></i> Kas Masuk</a>
				</li>
				<li class="separator">
					<i class="flaticon-right-arrow"></i>
				</li>
				<li class="nav-item">
					<a href="#"><i class="fas fa-info-circle"></i> List Kas Masuk</a>
				</li>
			</ul>
		</div>
		<div class="row">
			<div class="col-md-12">
				<div class="card">
					<div class="card-header">
						<h4 class="card-title"><i class="fas fa-clipboard-list"></i> List Kas Masuk</h4>
					</div>
					<div class="box-header" style="margin-left: 29px; margin-top: 8px;">
						<button type="submit" class="btn  btn-primary btn-sm btn-round" data-toggle="modal" data-target="#exampleModal"><i class="fas fa-plus-circle"></i> Tambah </button>

						<button type="button" class="btn btn-primary btn-sm btn-round btn-border" data-toggle="modal" data-target="#exampleModalEye"><i class="fas fa-eye"></i> Lihat Jumlah Pemasukan</button>

						{{-- <a href="{{ route('kasmasuk.exportexcel') }}" class="btn btn-sm btn-info" data-toggle="tooltip" data-placement="top" title="Cetak Excel">
						<i class="far fa-file-excel"></i> Cetak Excel
						</a> --}}
						<button type="button" class="btn btn-primary btn-border btn-sm btn-round" data-toggle="modal" data-target="#exampleModalExcel"><i class="far fa-file-excel"></i> Cetak Excel</button>

						<button type="button" class="btn btn-primary btn-border btn-sm btn-round" data-toggle="modal" data-target="#exampleModalPDF"><i class="fas fa-print"></i> Cetak PDF</button>

						{{-- <a href="{{ route('kasmasuk.exportpdf') }}" class="btn btn-sm btn-info" data-toggle="tooltip" data-placement="top" title="Cetak PDF">
						<i class="far fa-file-pdf"></i> Cetak PDF
						</a> --}}
					</div>
					<br>
				{{-- 	<div class="box-header" style="margin-left: 20%; margin-top: 8px;">
						<div class="row">

							<div class="col-md-3">
						
								{!! Form::number('tahun', \Carbon\Carbon::now()->year, ['class'=>'form-control input-pill']) !!}
								{!! $errors->first('tahun', '<p class="help-block">:message</p>') !!}
								
							</div>
							<div class="col-md-3">
								{!! Form::selectMonth('bulan', \Carbon\Carbon::now()->month, ['class'=>'form-control input-pill']) !!}
								{!! $errors->first('bulan', '<p class="help-block">:message</p>') !!}
							</div>
					

							<div class="col-md-2">
								<button id="display" type="button" class="form-control btn btn-primary" data-toggle="tooltip" data-placement="top" title="Display">Display</button>
							</div>
						</div>
					</div>  --}} 
					<div class="card-body">
						<div class="table-responsive">
							<table id="users-table" cellspacing="0" width="100%" class="table table-condensed " >
								<thead>
									<tr>
										<th>No</th>
										<th>Tanggal</th>
										<th>Nama</th>
										<th>Keterangan</th>
										<th>Jumlah</th>
										<th style="width: 14%">Action</th>
									</tr>
								</thead>
							</table>
				
						</div>
					</div>
				</div>
			</div>
			
		</div>
	</div>
</div>
@include('kasmasuk.modal.create')
@include('kasmasuk.modal.jumlahpem')
@include('kasmasuk.modal.exportpdf_modal')
@include('kasmasuk.modal.exportexcel_modal')
@endsection
@push('scripts')
<script>
$(document).ready(function() {
        var tableDetail = $('#users-table').DataTable({
        	  "columnDefs": [{
        	  "searchable": false,
        	  "orderable": false,
        	  "targets": 0,

        	  render: function (data, type, row, meta) {
        	    return meta.row + meta.settings._iDisplayStart + 1;
        	  }
        	}],
        	"aLengthMenu": [[5, 10, 25, 50, 75, 100, -1], [5, 10, 25, 50, 75, 100, "All"]],
        	"iDisplayLength": 10,
        	processing: true, 
        	responsive: true,
        	"order": [[1, 'asc']],
        	// "oLanguage": {
        	//   'sProcessing': '<div id="processing" style="margin: 0px; padding: 0px; position: fixed; right: 0px; top: 0px; width: 100%; height: 100%; background-color: rgb(102, 102, 102); z-index: 30001; opacity: 0.8;"><p style="position: absolute; color: White; top: 50%; left: 45%;"><img src="{{ asset('images/ajax-loader.gif') }}"></p></div>Processing...'
        	// },
            serverSide: true,
            ajax: '{{ route('kasmasuk.dashboard') }}',
            columns: [
                {data: null, name: null},
                { data: 'tgl', name: 'tgl' },
                { data: 'nama', name: 'nama' },
                { data: 'keterangan', name: 'keterangan' },
                { data: 'jumlah', name: 'jumlah' },
                { data: 'action', name: 'action' }
            ]


        });
       // $("#users-table").on('preXhr.dt', function(e, settings, data) {
       //   data.tahun = $('input[name="tahun"]').val();
       //   data.bulan = $('input[name="bulan"]').val();
       // });

       // $('#display').click( function () {
       // 	tableDetail.ajax.reload();
       // });
        
 
});

</script>



@endpush