routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::group(['middleware' => ['auth', 'checkRole:admin,user']], function() {
    Route::get('/dashboard', 'DashboardController@index')->name('dashboard.index');
    Route::get('/kasmasuk/json', 'KasMasukController@dashboard')->name('kasmasuk.dashboard');
    Route::resource('kasmasuk', 'KasMasukController');
    Route::get('/exportpdf', 'KasMasukController@exportpdf')->name('kasmasuk.exportpdf');
    Route::get('/exportpdfperiode', 'KasMasukController@exportpdfperiode')->name('kasmasuk.exportpdfperiode');
    Route::get('/exportexcel', 'KasMasukController@exportExcel')->name('kasmasuk.exportexcel');
    Route::get('/exportexcelper', 'KasMasukController@exportexcelper')->name('kasmasuk.exportexcelper');

    Route::get('/kaskeluar/json', 'KasKeluarController@dashboard')->name('kaskeluar.dashboard');
    Route::resource('kaskeluar','KasKeluarController');
    Route::get('/exportpdfkel', 'KasKeluarController@exportpdfkel')->name('kaskeluar.exportpdfkel');
    Route::get('/exportpdfperiodekel', 'KasKeluarController@exportpdfperiodekel')->name('kaskeluar.exportpdfperiodekel');
    Route::get('/exportexcelkel', 'KasKeluarController@exportExcelkel')->name('kaskeluar.exportexcelkel');
    Route::get('/exportexcelperkel', 'KasKeluarController@exportexcelperkel')->name('kaskeluar.exportexcelperkel');

    Route::get('/rekapitulasi','RekapitulasiController@index')->name('rekapitulasi.index');
    Route::get('/exportpdfrekap', 'RekapitulasiController@exportpdfrekap')->name('rekapitulasi.exportpdfrekap');
    Route::get('/exportpdfperioderekap', 'RekapitulasiController@exportpdfperioderekap')->name('rekapitulasi.exportpdfperioderekap');

    Route::get('/dashboarduser', 'ManajemenUserController@dashboard')->name('user.dashboard');
    Route::resource('/user', 'ManajemenUserController');

});
Route::group(['middleware' => ['auth', 'checkRole:admin,user']], function() {
     Route::get('/dashboard', 'DashboardController@index')->name('dashboard.index');
     Route::get('/dashboard', 'DashboardController@index')->name('dashboard.index');
     Route::get('/kasmasuk/json', 'KasMasukController@dashboard')->name('kasmasuk.dashboard');
     Route::resource('kasmasuk', 'KasMasukController');
     Route::get('/exportpdf', 'KasMasukController@exportpdf')->name('kasmasuk.exportpdf');
     Route::get('/exportpdfperiode', 'KasMasukController@exportpdfperiode')->name('kasmasuk.exportpdfperiode');
     Route::get('/exportexcel', 'KasMasukController@exportExcel')->name('kasmasuk.exportexcel');
     Route::get('/exportexcelper', 'KasMasukController@exportexcelper')->name('kasmasuk.exportexcelper');

     Route::get('/kaskeluar/json', 'KasKeluarController@dashboard')->name('kaskeluar.dashboard');
     Route::resource('kaskeluar','KasKeluarController');
     Route::get('/exportpdfkel', 'KasKeluarController@exportpdfkel')->name('kaskeluar.exportpdfkel');
     Route::get('/exportpdfperiodekel', 'KasKeluarController@exportpdfperiodekel')->name('kaskeluar.exportpdfperiodekel');
     Route::get('/exportexcelkel', 'KasKeluarController@exportExcelkel')->name('kaskeluar.exportexcelkel');
     Route::get('/exportexcelperkel', 'KasKeluarController@exportexcelperkel')->name('kaskeluar.exportexcelperkel');

     Route::get('/rekapitulasi','RekapitulasiController@index')->name('rekapitulasi.index');
     Route::get('/exportpdfrekap', 'RekapitulasiController@exportpdfrekap')->name('rekapitulasi.exportpdfrekap');
     Route::get('/exportpdfperioderekap', 'RekapitulasiController@exportpdfperioderekap')->name('rekapitulasi.exportpdfperioderekap');
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','role','alamat','notelp','foto'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

resources/views/user/_form.blade.php
<form action="{{ route('user.store') }}" method="post" enctype="multipart/form-data">
	{{ csrf_field() }}
	<div class="form-group">
		<label for="pillInput">Nama</label>
		<input type="text" name="name" autocomplete="true" class="form-control input-pill"  id="pillInput" placeholder="Nama" required>
	</div>

	<div class="form-group">
		<label for="pillInput">Alamat</label>
		<input type="text" name="alamat" class="form-control input-pill"  id="pillInput" placeholder="Alamat" required>
	</div>

	<div class="form-group">
		<label for="pillInput">No Telepon</label>
		<input type="text" name="notelp" class="form-control input-pill" id="pillInput" placeholder="No Telepon" required>
	</div>
	<div class="form-group">
		<label for="pillInput">Email</label>
		<input type="email" name="email" class="form-control input-pill" id="pillInput" placeholder="Email" required>
	</div>
	<div class="form-group">
		<label for="pillInput">Foto</label>
		<input type="file" name="foto" class="form-control input-pill" id="pillInput" placeholder="foto" required>
	</div>
	<br>
	<div class="modal-footer">

		<button type="submit" class="btn btn-sm btn-primary "><i class="fas fa-save"></i> Simpan</button>
		<button type="button" class="btn btn-sm btn-primary btn-border" data-dismiss="modal">Batal</button>
	</div>
</form>

resources/views/user/edit.blade.php
@extends('layouts.master')
@section('title','Edit Data Data User')
@section('content')
<div class="content">
	<div class="page-inner">
		<div class="page-header">
			<h4 class="page-title"><i class="far fa-file-alt"></i> Data User</h4>
			<ul class="breadcrumbs">
				<li class="nav-home">
					<a href="{{ route('dashboard.index') }}">
						<i class="flaticon-home"></i>
					</a>
				</li>
				<li class="separator">
					<i class="flaticon-right-arrow"></i>
				</li>
				<li class="nav-item">
					<a href="#"><i class="far fa-file-alt"></i> Data User</a>
				</li>
				<li class="separator">
					<i class="flaticon-right-arrow"></i>
				</li>
				<li class="nav-item">
					<a href="#"><i class="fas fa-info-circle"></i> List Data User</a>
				</li>
				<li class="separator">
					<i class="flaticon-right-arrow"></i>
				</li>
				<li class="nav-item">
					<a href="#"><i class="fas fa-edit"></i> Ubah Data User</a>
				</li>
			</ul>
		</div>
		<div class="row">
			<div class="col-md-12">
				<div class="card">
					<div class="card-header">
						<h4 class="card-title"><i class="fas fa-edit"></i> Ubah Data User</h4>
					</div>
					
					<div class="card-body">
						<form action="{{ route('user.update', $user->id) }}" method="post" enctype="multipart/form-data">
							{{ csrf_field() }}
							{{ method_field('put') }}
							<div class="form-group">
								<label for="">Nama</label>
								<input type="text" name="name" value="{{ $user->name }}" class="form-control" id=""  placeholder="Nama">
							</div>
							<div class="form-group">
								<label for="">Alamat</label>
								<input type="text" name="alamat" value="{{ $user->alamat }}" class="form-control"  placeholder="Alamat">
							</div>
							<div class="form-group">
								<label for="">No HP</label>
								<input type="text" name="notelp" value="{{ $user->notelp }}" class="form-control"  placeholder="Keterangan">
							</div>
							<div class="form-group">
								<label for="">Email</label>
								<input type="email" name="email" value="{{ $user->email }}" class="form-control"  placeholder="Email">
							</div>
							<div class="form-group">
								<label for="">foto</label>
								<input type="file" name="foto"  class="form-control"  placeholder="foto">
							</div>
							<br>
							<div class="box-header" style="margin-left: 14px;">
								<button type="submit" class="btn btn-sm btn-info"><i class="fas fa-save"></i> Simpan</button>
								<a href="{{ route('user.index') }}" class="btn btn-sm btn-warning" title="">Kembali</a>
							</div>
							
						</form>
					</div>
				</div>
			</div>
			
		</div>
	</div>
</div>
@endsection

resources/views/user/index.blade.php
@extends('layouts.master')
@section('title',' Data User')
@section('content')
<div class="content">
	<div class="page-inner">
		<div class="page-header">
			<h4 class="page-title"><i class="far fa-file-alt"></i> Data User</h4>
			<ul class="breadcrumbs">
				<li class="nav-home">
					<a href="{{ route('dashboard.index') }}">
						<i class="flaticon-home"></i>
					</a>
				</li>
				<li class="separator">
					<i class="flaticon-right-arrow"></i>
				</li>
				<li class="nav-item">
					<a href="#"><i class="far fa-file-alt"></i> Data User</a>
				</li>
				<li class="separator">
					<i class="flaticon-right-arrow"></i>
				</li>
				<li class="nav-item">
					<a href="#"><i class="fas fa-info-circle"></i> List Data User</a>
				</li>
			</ul>
		</div>
		<div class="row">
			<div class="col-md-12">
				<div class="card">
					<div class="card-header">
						<h4 class="card-title"><i class="fas fa-clipboard-list"></i> List Data User</h4>
					</div>
					<div class="box-header" style="margin-left: 29px; margin-top: 8px;">
						<button type="submit" class="btn  btn-primary btn-sm btn-round" data-toggle="modal" data-target="#exampleModal"><i class="fas fa-plus-circle"></i> Tambah </button>
						{{-- <a href="{{ route('kasmasuk.exportexcel') }}" class="btn btn-sm btn-info" data-toggle="tooltip" data-placement="top" title="Cetak Excel">
						<i class="far fa-file-excel"></i> Cetak Excel
						</a> --}}
{{-- 						<button type="button" class="btn btn-primary btn-border btn-sm btn-round" data-toggle="modal" data-target="#exampleModalExcel"><i class="far fa-file-excel"></i> Cetak Excel</button>

						<button type="button" class="btn btn-primary btn-border btn-sm btn-round" data-toggle="modal" data-target="#exampleModalPDF"><i class="fas fa-print"></i> Cetak PDF</button> --}}

						{{-- <a href="{{ route('kasmasuk.exportpdf') }}" class="btn btn-sm btn-info" data-toggle="tooltip" data-placement="top" title="Cetak PDF">
						<i class="far fa-file-pdf"></i> Cetak PDF
						</a> --}}
					</div>
					<br>
				{{-- 	<div class="box-header" style="margin-left: 20%; margin-top: 8px;">
						<div class="row">

							<div class="col-md-3">
						
								{!! Form::number('tahun', \Carbon\Carbon::now()->year, ['class'=>'form-control input-pill']) !!}
								{!! $errors->first('tahun', '<p class="help-block">:message</p>') !!}
								
							</div>
							<div class="col-md-3">
								{!! Form::selectMonth('bulan', \Carbon\Carbon::now()->month, ['class'=>'form-control input-pill']) !!}
								{!! $errors->first('bulan', '<p class="help-block">:message</p>') !!}
							</div>
					

							<div class="col-md-2">
								<button id="display" type="button" class="form-control btn btn-primary" data-toggle="tooltip" data-placement="top" title="Display">Display</button>
							</div>
						</div>
					</div>  --}} 
					<div class="card-body">
						<div class="table-responsive">
							<table id="users-table" cellspacing="0" width="100%" class="table table-condensed" >
								<thead>
									<tr>
										<th>No</th>
										<th>Role</th>
										<th>Foto</th>
										<th>Nama</th>
										<th>Alamat</th>
										<th>No Hp</th>
										<th>Email</th>
										<th style="width: 20%">Action</th>
									</tr>
								</thead>
								<tbody>
									@php $no = 1 ;@endphp
									@foreach($user as $row)
									<tr>
										<td>{{ $no++ }}</td>
										<td>{{ $row->role }}</td>
										<td>
										<center>
											@if($row->foto != null)
											 <img src="images/{{ $row->foto }}" alt="" width="50" height="50">
											@else 
											   <img src="images/man-1.png" alt="" width="50" height="50">
											@endif   
										</center>
										</td>
										<td>{{ $row->name }}</td>
										<td>{{ $row->alamat }}</td>
										<td>{{ $row->notelp }}</td>
										<td>{{ $row->email }}</td>
										<td>
											<a href="{{ route('user.edit', $row->id) }}" title="" class="btn btn-primary btn-sm btn-round btn-border"><i class="fas fa-edit"></i></a>
											<div class="pull-right">
												<form action="{{ route('user.destroy', $row->id) }}" method="post">
												{{ csrf_field() }}
												{{ method_field('DELETE') }}
												<button type="submit" onclick="return confirm('Yakin ?')" class="btn btn-danger btn-sm btn-round"><i class="fas fa-trash"></i></button>
											</form>
											</div>
											
										</td>
										
									</tr>
									@endforeach
								</tbody>
							</table>
				
						</div>
					</div>
				</div>
			</div>
			
		</div>
	</div>
</div>
@include('user.modal.create')
@endsection
@push('scripts')
<script>
$(document).ready(function() {
     $('#users-table').DataTable();

 
});

</script>



@endpush