routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::group(['middleware' => ['auth', 'checkRole:admin,user']], function() {
    Route::get('/dashboard', 'DashboardController@index')->name('dashboard.index');
    Route::get('/kasmasuk/json', 'KasMasukController@dashboard')->name('kasmasuk.dashboard');
    Route::resource('kasmasuk', 'KasMasukController');
    Route::get('/exportpdf', 'KasMasukController@exportpdf')->name('kasmasuk.exportpdf');
    Route::get('/exportpdfperiode', 'KasMasukController@exportpdfperiode')->name('kasmasuk.exportpdfperiode');
    Route::get('/exportexcel', 'KasMasukController@exportExcel')->name('kasmasuk.exportexcel');
    Route::get('/exportexcelper', 'KasMasukController@exportexcelper')->name('kasmasuk.exportexcelper');

    Route::get('/kaskeluar/json', 'KasKeluarController@dashboard')->name('kaskeluar.dashboard');
    Route::resource('kaskeluar','KasKeluarController');
    Route::get('/exportpdfkel', 'KasKeluarController@exportpdfkel')->name('kaskeluar.exportpdfkel');
    Route::get('/exportpdfperiodekel', 'KasKeluarController@exportpdfperiodekel')->name('kaskeluar.exportpdfperiodekel');
    Route::get('/exportexcelkel', 'KasKeluarController@exportExcelkel')->name('kaskeluar.exportexcelkel');
    Route::get('/exportexcelperkel', 'KasKeluarController@exportexcelperkel')->name('kaskeluar.exportexcelperkel');

    Route::get('/rekapitulasi','RekapitulasiController@index')->name('rekapitulasi.index');
    Route::get('/exportpdfrekap', 'RekapitulasiController@exportpdfrekap')->name('rekapitulasi.exportpdfrekap');
    Route::get('/exportpdfperioderekap', 'RekapitulasiController@exportpdfperioderekap')->name('rekapitulasi.exportpdfperioderekap');

    Route::get('/dashboarduser', 'ManajemenUserController@dashboard')->name('user.dashboard');
    Route::resource('/user', 'ManajemenUserController');

});
Route::group(['middleware' => ['auth', 'checkRole:admin,user']], function() {
     Route::get('/dashboard', 'DashboardController@index')->name('dashboard.index');
     Route::get('/dashboard', 'DashboardController@index')->name('dashboard.index');
     Route::get('/kasmasuk/json', 'KasMasukController@dashboard')->name('kasmasuk.dashboard');
     Route::resource('kasmasuk', 'KasMasukController');
     Route::get('/exportpdf', 'KasMasukController@exportpdf')->name('kasmasuk.exportpdf');
     Route::get('/exportpdfperiode', 'KasMasukController@exportpdfperiode')->name('kasmasuk.exportpdfperiode');
     Route::get('/exportexcel', 'KasMasukController@exportExcel')->name('kasmasuk.exportexcel');
     Route::get('/exportexcelper', 'KasMasukController@exportexcelper')->name('kasmasuk.exportexcelper');

     Route::get('/kaskeluar/json', 'KasKeluarController@dashboard')->name('kaskeluar.dashboard');
     Route::resource('kaskeluar','KasKeluarController');
     Route::get('/exportpdfkel', 'KasKeluarController@exportpdfkel')->name('kaskeluar.exportpdfkel');
     Route::get('/exportpdfperiodekel', 'KasKeluarController@exportpdfperiodekel')->name('kaskeluar.exportpdfperiodekel');
     Route::get('/exportexcelkel', 'KasKeluarController@exportExcelkel')->name('kaskeluar.exportexcelkel');
     Route::get('/exportexcelperkel', 'KasKeluarController@exportexcelperkel')->name('kaskeluar.exportexcelperkel');

     Route::get('/rekapitulasi','RekapitulasiController@index')->name('rekapitulasi.index');
     Route::get('/exportpdfrekap', 'RekapitulasiController@exportpdfrekap')->name('rekapitulasi.exportpdfrekap');
     Route::get('/exportpdfperioderekap', 'RekapitulasiController@exportpdfperioderekap')->name('rekapitulasi.exportpdfperioderekap');
});

resources/views/_menu/content.blade.php
<div class="content">
	<div class="panel-header bg-primary-gradient">
		<div class="page-inner py-5">
			<div class="d-flex align-items-left align-items-md-center flex-column flex-md-row">
				<div>
					<h2 class="text-white pb-2 fw-bold">Dashboard</h2>
					<h5 class="text-white op-7 mb-2">Aplikasi Pengelolaan Kas Masjid</h5>
				</div>
			</div>
		</div>
	</div>
	<div class="page-inner mt--5">
		<div class="row mt--2">
			<div class="col-md-12">
				<div class="card full-height">
					<div class="card-body">
						<div class="card-title">Overall statistics</div>
						<div class="card-category">Daily information about statistics in system</div>
						<div class="d-flex flex-wrap justify-content-around pb-2 pt-4">
							<div class="col-sm-3 col-md-3">
								<div class="card card-stats card-primary card-round">
									<div class="card-body">
										<div class="row">
											<div class="col-5">
												<div class="icon-big text-center">
													<i class="flaticon-users"></i>
												</div>
											</div>
											<div class="col-7 col-stats">
												<div class="numbers">
													<p class="card-category">Visitors</p>
													<h4 class="card-title">1,294</h4>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>		
							<div class="col-sm-3 col-md-3">
								<div class="card card-stats card-primary card-round">
									<div class="card-body">
										<div class="row">
											<div class="col-5">
												<div class="icon-big text-center">
													<i class="flaticon-users"></i>
												</div>
											</div>
											<div class="col-7 col-stats">
												<div class="numbers">
													<p class="card-category">Visitors</p>
													<h4 class="card-title">1,294</h4>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>	
							<div class="col-sm-3 col-md-3">
								<div class="card card-stats card-primary card-round">
									<div class="card-body">
										<div class="row">
											<div class="col-5">
												<div class="icon-big text-center">
													<i class="flaticon-users"></i>
												</div>
											</div>
											<div class="col-7 col-stats">
												<div class="numbers">
													<p class="card-category">Visitors</p>
													<h4 class="card-title">1,294</h4>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>	
						</div>
					</div>
				</div>
			</div>

	{{-- 	<div class="row">
			<div class="col-md-6">
				<div class="card full-height">
					<div class="card-header">
						<div class="card-title">Feed Activity</div>
					</div>
					<div class="card-body">
						<ol class="activity-feed">
							<li class="feed-item feed-item-secondary">
								<time class="date" datetime="9-25">Sep 25</time>
								<span class="text">Responded to need <a href="#">"Volunteer opportunity"</a></span>
							</li>
							<li class="feed-item feed-item-success">
								<time class="date" datetime="9-24">Sep 24</time>
								<span class="text">Added an interest <a href="#">"Volunteer Activities"</a></span>
							</li>
							<li class="feed-item feed-item-info">
								<time class="date" datetime="9-23">Sep 23</time>
								<span class="text">Joined the group <a href="single-group.php">"Boardsmanship Forum"</a></span>
							</li>
							<li class="feed-item feed-item-warning">
								<time class="date" datetime="9-21">Sep 21</time>
								<span class="text">Responded to need <a href="#">"In-Kind Opportunity"</a></span>
							</li>
							<li class="feed-item feed-item-danger">
								<time class="date" datetime="9-18">Sep 18</time>
								<span class="text">Created need <a href="#">"Volunteer Opportunity"</a></span>
							</li>
							<li class="feed-item">
								<time class="date" datetime="9-17">Sep 17</time>
								<span class="text">Attending the event <a href="single-event.php">"Some New Event"</a></span>
							</li>
						</ol>
					</div>
				</div>
			</div>
			<div class="col-md-6">
				<div class="card full-height">
					<div class="card-header">
						<div class="card-head-row">
							<div class="card-title">Support Tickets</div>
							<div class="card-tools">
								<ul class="nav nav-pills nav-secondary nav-pills-no-bd nav-sm" id="pills-tab" role="tablist">
									<li class="nav-item">
										<a class="nav-link" id="pills-today" data-toggle="pill" href="#pills-today" role="tab" aria-selected="true">Today</a>
									</li>
									<li class="nav-item">
										<a class="nav-link active" id="pills-week" data-toggle="pill" href="#pills-week" role="tab" aria-selected="false">Week</a>
									</li>
									<li class="nav-item">
										<a class="nav-link" id="pills-month" data-toggle="pill" href="#pills-month" role="tab" aria-selected="false">Month</a>
									</li>
								</ul>
							</div>
						</div>
					</div>
					<div class="card-body">
						<div class="d-flex">
							<div class="avatar avatar-online">
								<span class="avatar-title rounded-circle border border-white bg-info">J</span>
							</div>
							<div class="flex-1 ml-3 pt-1">
								<h6 class="text-uppercase fw-bold mb-1">Joko Subianto <span class="text-warning pl-3">pending</span></h6>
								<span class="text-muted">I am facing some trouble with my viewport. When i start my</span>
							</div>
							<div class="float-right pt-1">
								<small class="text-muted">8:40 PM</small>
							</div>
						</div>
						<div class="separator-dashed"></div>
						<div class="d-flex">
							<div class="avatar avatar-offline">
								<span class="avatar-title rounded-circle border border-white bg-secondary">P</span>
							</div>
							<div class="flex-1 ml-3 pt-1">
								<h6 class="text-uppercase fw-bold mb-1">Prabowo Widodo <span class="text-success pl-3">open</span></h6>
								<span class="text-muted">I have some query regarding the license issue.</span>
							</div>
							<div class="float-right pt-1">
								<small class="text-muted">1 Day Ago</small>
							</div>
						</div>
						<div class="separator-dashed"></div>
						<div class="d-flex">
							<div class="avatar avatar-away">
								<span class="avatar-title rounded-circle border border-white bg-danger">L</span>
							</div>
							<div class="flex-1 ml-3 pt-1">
								<h6 class="text-uppercase fw-bold mb-1">Lee Chong Wei <span class="text-muted pl-3">closed</span></h6>
								<span class="text-muted">Is there any update plan for RTL version near future?</span>
							</div>
							<div class="float-right pt-1">
								<small class="text-muted">2 Days Ago</small>
							</div>
						</div>
						<div class="separator-dashed"></div>
						<div class="d-flex">
							<div class="avatar avatar-offline">
								<span class="avatar-title rounded-circle border border-white bg-secondary">P</span>
							</div>
							<div class="flex-1 ml-3 pt-1">
								<h6 class="text-uppercase fw-bold mb-1">Peter Parker <span class="text-success pl-3">open</span></h6>
								<span class="text-muted">I have some query regarding the license issue.</span>
							</div>
							<div class="float-right pt-1">
								<small class="text-muted">2 Day Ago</small>
							</div>
						</div>
						<div class="separator-dashed"></div>
						<div class="d-flex">
							<div class="avatar avatar-away">
								<span class="avatar-title rounded-circle border border-white bg-danger">L</span>
							</div>
							<div class="flex-1 ml-3 pt-1">
								<h6 class="text-uppercase fw-bold mb-1">Logan Paul <span class="text-muted pl-3">closed</span></h6>
								<span class="text-muted">Is there any update plan for RTL version near future?</span>
							</div>
							<div class="float-right pt-1">
								<small class="text-muted">2 Days Ago</small>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div> --}}
	</div>
</div>

resources/views/_menu/custome.blade.php
<div class="custom-template">
	<div class="title">Settings</div>
	<div class="custom-content">
		<div class="switcher">
			<div class="switch-block">
				<h4>Logo Header</h4>
				<div class="btnSwitch">
					<button type="button" class="changeLogoHeaderColor" data-color="dark"></button>
					<button type="button" class="selected changeLogoHeaderColor" data-color="blue"></button>
					<button type="button" class="changeLogoHeaderColor" data-color="purple"></button>
					<button type="button" class="changeLogoHeaderColor" data-color="light-blue"></button>
					<button type="button" class="changeLogoHeaderColor" data-color="green"></button>
					<button type="button" class="changeLogoHeaderColor" data-color="orange"></button>
					<button type="button" class="changeLogoHeaderColor" data-color="red"></button>
					<button type="button" class="changeLogoHeaderColor" data-color="white"></button>
					<br/>
					<button type="button" class="changeLogoHeaderColor" data-color="dark2"></button>
					<button type="button" class="changeLogoHeaderColor" data-color="blue2"></button>
					<button type="button" class="changeLogoHeaderColor" data-color="purple2"></button>
					<button type="button" class="changeLogoHeaderColor" data-color="light-blue2"></button>
					<button type="button" class="changeLogoHeaderColor" data-color="green2"></button>
					<button type="button" class="changeLogoHeaderColor" data-color="orange2"></button>
					<button type="button" class="changeLogoHeaderColor" data-color="red2"></button>
				</div>
			</div>
			<div class="switch-block">
				<h4>Navbar Header</h4>
				<div class="btnSwitch">
					<button type="button" class="changeTopBarColor" data-color="dark"></button>
					<button type="button" class="changeTopBarColor" data-color="blue"></button>
					<button type="button" class="changeTopBarColor" data-color="purple"></button>
					<button type="button" class="changeTopBarColor" data-color="light-blue"></button>
					<button type="button" class="changeTopBarColor" data-color="green"></button>
					<button type="button" class="changeTopBarColor" data-color="orange"></button>
					<button type="button" class="changeTopBarColor" data-color="red"></button>
					<button type="button" class="changeTopBarColor" data-color="white"></button>
					<br/>
					<button type="button" class="changeTopBarColor" data-color="dark2"></button>
					<button type="button" class="selected changeTopBarColor" data-color="blue2"></button>
					<button type="button" class="changeTopBarColor" data-color="purple2"></button>
					<button type="button" class="changeTopBarColor" data-color="light-blue2"></button>
					<button type="button" class="changeTopBarColor" data-color="green2"></button>
					<button type="button" class="changeTopBarColor" data-color="orange2"></button>
					<button type="button" class="changeTopBarColor" data-color="red2"></button>
				</div>
			</div>
			<div class="switch-block">
				<h4>Sidebar</h4>
				<div class="btnSwitch">
					<button type="button" class="selected changeSideBarColor" data-color="white"></button>
					<button type="button" class="changeSideBarColor" data-color="dark"></button>
					<button type="button" class="changeSideBarColor" data-color="dark2"></button>
				</div>
			</div>
			<div class="switch-block">
				<h4>Background</h4>
				<div class="btnSwitch">
					<button type="button" class="changeBackgroundColor" data-color="bg2"></button>
					<button type="button" class="changeBackgroundColor selected" data-color="bg1"></button>
					<button type="button" class="changeBackgroundColor" data-color="bg3"></button>
					<button type="button" class="changeBackgroundColor" data-color="dark"></button>
				</div>
			</div>
		</div>
	</div>
	<div class="custom-toggle">
		<i class="flaticon-settings"></i>
	</dassets/css/demo.cssiv>

resources/views/_menu/footer.blade.php
{{-- <footer style="bottom: 0px;" class="footer">
	<div class="container-fluid">
		<nav class="pull-left">
			
		</nav>
		<div class="copyright ml-auto">
			2019 &copy; DKM Masjid Jamie Baetul Anwar</a>
		</div>				
	</div>
</footer> --}}

resources/views/_menu/header.blade.php
<head>
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<title>@yield('title')</title>
	<meta content='width=device-width, initial-scale=1.0, shrink-to-fit=no' name='viewport' />
	<link rel="icon" href="{{asset('images/logodkm.jpg')}}" type="image/x-icon"/>

	<!-- Fonts and icons -->
	<script src="{{asset('assets/js/plugin/webfont/webfont.min.js')}}"></script>
	<script>
		WebFont.load({
			google: {"families":["Lato:300,400,700,900"]},
			custom: {"families":["Flaticon", "Font Awesome 5 Solid", "Font Awesome 5 Regular", "Font Awesome 5 Brands", "simple-line-icons"], urls: ['{{asset('assets/css/fonts.min.css')}}']},
			active: function() {
				sessionStorage.fonts = true;
			}
		});
	</script>

	<!-- CSS Files -->
	<link rel="stylesheet" href="{{asset('assets/css/bootstrap.min.css')}}">
	<link rel="stylesheet" href="{{asset('assets/css/atlantis.min.css')}}">
	<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.css">
	{!! Charts::assets() !!}
	

	<!-- CSS Just for demo purpose, don't include it in your project -->
	<link rel="stylesheet" href="{{asset('assets/css/demo.css')}}">
</head>

resources/views/_menu/main-header.blade.php
<div class="main-header">
	<!-- Logo Header -->
	<div class="logo-header" data-background-color="blue">
		
		<a href="index.html" class="logo">
			{{-- <img src="{{asset('images/logodkm.png')}}" width="40px"  height="40px" alt="navbar brand" class="navbar-brand"> --}}
			<h3 style="color: white; margin-top: 15%; margin-left: 30%;"><b>MASTERKAS</b></h3>
		{{-- 	<p style="color: white">Dkm Masjid</p> --}}
		</a>
		<button class="navbar-toggler sidenav-toggler ml-auto" type="button" data-toggle="collapse" data-target="collapse" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon">
				<i class="icon-menu"></i>
			</span>
		</button>
		<button class="topbar-toggler more"><i class="icon-options-vertical"></i></button>
		<div class="nav-toggle">
			<button class="btn btn-toggle toggle-sidebar">
				<i class="icon-menu"></i>
			</button>
		</div>
	</div>
	<!-- End Logo Header -->

	<!-- Navbar Header -->
	@include('_menu.navbar')
	<!-- End Navbar -->
</div>

resources/views/_menu/navbar.blade.php
<nav class="navbar navbar-header navbar-expand-lg" data-background-color="blue2">
	
	<div class="container-fluid">
		<div class="collapse" id="search-nav">
		</div>
		<ul class="navbar-nav topbar-nav ml-md-auto align-items-center">
			<li class="nav-item toggle-nav-search hidden-caret">
				<a class="nav-link" data-toggle="collapse" href="#search-nav" role="button" aria-expanded="false" aria-controls="search-nav">
					<i class="fa fa-search"></i>
				</a>
			</li>
			<li class="nav-item dropdown hidden-caret">
				<a class="dropdown-toggle profile-pic" data-toggle="dropdown" href="#" aria-expanded="false">
					<div class="avatar-sm">
						<img src="{{asset('images/man-1.png')}}"alt="..." class="avatar-img rounded-circle">
					</div>
				</a>
				<ul class="dropdown-menu dropdown-user animated fadeIn">
					<div class="dropdown-user-scroll scrollbar-outer">
						<li>
							<div class="user-box">
								<div class="avatar-lg"><img src="{{asset('images/man-1.png')}}" alt="image profile" class="avatar-img rounded"></div>
								<div class="u-text">
									<h4>{{ Auth::user()->name }}</h4>
									<p class="text-muted">{{ Auth::user()->email }}</p><a href="profile.html" class="btn btn-xs btn-secondary btn-sm">View Profile</a>
								</div>
							</div>
						</li>
						<li>
							<div class="dropdown-divider"></div>
							<a class="dropdown-item" href="#">My Profile</a>
							<div class="dropdown-divider"></div>
							<a class="dropdown-item" href="{{ route('logout') }}" 
							onclick="event.preventDefault();
							document.getElementById('logout-form').submit();">

							Logout
						    </a>
						    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
						        {{ csrf_field() }}
						    </form>
						</li>
					</div>
				</ul>
			</li>
		</ul>
	</div>
</nav>

resources/views/_menu/script.blade.php
<script src="{{asset('assets/js/core/jquery.3.2.1.min.js')}}"></script>
<script src="{{asset('assets/js/core/popper.min.js')}}"></script>
<script src="{{asset('assets/js/core/bootstrap.min.js')}}"></script>

<!-- jQuery UI -->
<script src="{{asset('assets/js/plugin/jquery-ui-1.12.1.custom/jquery-ui.min.js')}}"></script>
<script src="{{asset('assets/js/plugin/jquery-ui-touch-punch/jquery.ui.touch-punch.min.js')}}"></script>

<!-- jQuery Scrollbar -->
<script src="{{asset('assets/js/plugin/jquery-scrollbar/jquery.scrollbar.min.js')}}"></script>


<!-- Chart JS -->
<script src="{{asset('assets/js/plugin/chart.js/chart.min.js')}}"></script>

<!-- jQuery Sparkline -->
<script src="{{asset('assets/js/plugin/jquery.sparkline/jquery.sparkline.min.js')}}"></script>

<!-- Chart Circle -->
<script src="{{asset('assets/js/plugin/chart-circle/circles.min.js')}}"></script>

<!-- Datatables -->
{{-- <script src="{{ asset('js/dataTables.bootstrap.min.js') }}"></script> --}}
<script src="{{asset('assets/js/plugin/datatables/datatables.min.js')}}"></script>

<!-- Bootstrap Notify -->
<script src="{{asset('assets/js/plugin/bootstrap-notify/bootstrap-notify.min.js')}}"></script>

<!-- jQuery Vector Maps -->
{{-- <script src="{{asset('assets/js/plugin/jqvmap/jquery.vmap.min.js')}}"></script>
<script src="{{asset('assets/js/plugin/jqvmap/maps/jquery.vmap.world.js')}}"></script> --}}

<!-- Sweet Alert -->
{{-- <script src="{{asset('assets/js/plugin/sweetalert/sweetalert.min.js')}}"></script> --}}
<script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js"></script>
{{-- <script src="https://code.highcharts.com/highcharts.js"></script> --}}

<!-- Atlantis JS -->
<script src="{{asset('assets/js/atlantis.min.js')}}"></script>

<!-- Atlantis DEMO methods, don't include it in your project! -->
<script src="{{asset('assets/js/setting-demo.js')}}"></script>
{{-- <script src="{{asset('assets/js/demo.js')}}"></script> --}}
@include('sweet::alert')
@yield('footer')
@stack('scripts')
{{-- <script>
	Circles.create({
		id:'circles-1',
		radius:45,
		value:60,
		maxValue:100,
		width:7,
		text: 5,
		colors:['#f1f1f1', '#FF9E27'],
		duration:400,
		wrpClass:'circles-wrp',
		textClass:'circles-text',
		styleWrapper:true,
		styleText:true
	})

	Circles.create({
		id:'circles-2',
		radius:45,
		value:70,
		maxValue:100,
		width:7,
		text: 36,
		colors:['#f1f1f1', '#2BB930'],
		duration:400,
		wrpClass:'circles-wrp',
		textClass:'circles-text',
		styleWrapper:true,
		styleText:true
	})

	Circles.create({
		id:'circles-3',
		radius:45,
		value:40,
		maxValue:100,
		width:7,
		text: 12,
		colors:['#f1f1f1', '#F25961'],
		duration:400,
		wrpClass:'circles-wrp',
		textClass:'circles-text',
		styleWrapper:true,
		styleText:true
	})

	var totalIncomeChart = document.getElementById('totalIncomeChart').getContext('2d');

	var mytotalIncomeChart = new Chart(totalIncomeChart, {
		type: 'bar',
		data: {
			labels: ["S", "M", "T", "W", "T", "F", "S", "S", "M", "T"],
			datasets : [{
				label: "Total Income",
				backgroundColor: '#ff9e27',
				borderColor: 'rgb(23, 125, 255)',
				data: [6, 4, 9, 5, 4, 6, 4, 3, 8, 10],
			}],
		},
		options: {
			responsive: true,
			maintainAspectRatio: false,
			legend: {
				display: false,
			},
			scales: {
				yAxes: [{
					ticks: {
						display: false //this will remove only the label
					},
					gridLines : {
						drawBorder: false,
						display : false
					}
				}],
				xAxes : [ {
					gridLines : {
						drawBorder: false,
						display : false
					}
				}]
			},
		}
	});

	$('#lineChart').sparkline([105,103,123,100,95,105,115], {
		type: 'line',
		height: '70',
		width: '100%',
		lineWidth: '2',
		lineColor: '#ffa534',
		fillColor: 'rgba(255, 165, 52, .14)'
	});
</script> --}}

resources/views/_menu/sidebar.blade.php
<div class="row">
	<div class="sidebar" data-background-color='dark2'>
		<div class="sidebar-wrapper scrollbar scrollbar-inner">
			<div class="sidebar-content">
				<div class="user">
					<div class="avatar-sm float-left mr-2">
						<img src="{{asset('images/man-1.png')}}" alt="..." class="avatar-img rounded-circle">
					</div>
					<div class="info">
						<a data-toggle="collapse" href="#collapseExample" aria-expanded="true">
							<span>
								Welcome
								<span class="user-level">{{ Auth::user()->role  }}</span>
								<span class="caret"></span>
							</span>
						</a>
						<div class="clearfix"></div>
						<div class="collapse in" id="collapseExample">
							<ul class="nav">
								<li>
									<a href="#profile">
										<span class="link-collapse">My Profile</span>
									</a>
								</li>
								<li>
									<a href="#edit">
										<span class="link-collapse">Edit Profile</span>
									</a>
								</li>
								<li>
									<a href="#settings">
										<span class="link-collapse">Settings</span>
									</a>
								</li>
							</ul>
						</div>
					</div>
				</div>
				<ul class="nav nav-warning">
					<li class="nav-item">
						<a href="{{ route('dashboard.index') }}" class="collapsed" aria-expanded="false">
							<i class="fas fa-home"></i>
							<p>Dashboard</p>
							{{-- 	<span class="caret"></span> --}}
						</a>
					</li>
					{{-- 	<li class="nav-section">
						<span class="sidebar-mini-icon">
							<i class="fa fa-ellipsis-h"></i>
						</span>
					</li> --}}
					<li class="nav-item">
						<a href="{{ route('kasmasuk.index') }}">
							<i class="fas fa-file-signature"></i>
							<p>Kas Masuk</p>
						</a>
					</li>
					<li class="nav-item">
						<a  href="{{ route('kaskeluar.index') }}">
							<i class="fas fa-file-signature"></i>
							<p>Kas Keluar</p>
						</a>
					</li>
					<li class="nav-item">
						<a  href="{{ route('rekapitulasi.index') }}">
							<i class="fas fa-file-signature"></i>
							<p>Rekapitulasi</p>
						</a>
					</li>
					@if(Auth::user()->role == "admin")
					<li class="nav-item">
						<a  href="{{ route('user.index') }}">
							<i class="fas fa-users"></i>
							<p>Manajemen User</p>
						</a>
					</li>
					@endif
					<li class="nav-item">
						<a data-toggle="collapse" href="{{ route('logout') }}" onclick="event.preventDefault();
							document.getElementById('logout-form').submit();">
							<i class="fas fa-sign-out-alt"></i>
							<p>Logout</p>
							<form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
								{{ csrf_field() }}
							</form>
						</a>
					</li>
				</ul>
			</div>
		</div>
	</div>
</div>